"""
Quick test client for the AI NFT Minter API
Tests the API endpoints to ensure everything is working
"""

import requests
import json
import time

BASE_URL = "http://localhost:8000"

print("🧪 Testing AI NFT Minter API")
print("=" * 60)

# Test 1: Root endpoint
print("\n1️⃣  Testing root endpoint...")
try:
    response = requests.get(f"{BASE_URL}/")
    if response.status_code == 200:
        print("   ✅ Root endpoint working")
        data = response.json()
        print(f"   API: {data.get('name')}")
        print(f"   Version: {data.get('version')}")
    else:
        print(f"   ❌ Failed: {response.status_code}")
except Exception as e:
    print(f"   ❌ Error: {e}")
    print(f"   💡 Make sure the server is running: python main.py")
    exit(1)

# Test 2: Health check
print("\n2️⃣  Testing health endpoint...")
try:
    response = requests.get(f"{BASE_URL}/health")
    if response.status_code == 200:
        data = response.json()
        print(f"   ✅ Health: {data.get('status')}")
        print(f"   API Configured: {data.get('api_configured')}")
        if not data.get('api_configured'):
            print(f"   ⚠️  GOOGLE_API_KEY not configured!")
    else:
        print(f"   ❌ Failed: {response.status_code}")
except Exception as e:
    print(f"   ❌ Error: {e}")

# Test 3: Generate NFT (only if API is configured)
print("\n3️⃣  Testing NFT generation...")
health_response = requests.get(f"{BASE_URL}/health")
if health_response.json().get('api_configured'):
    try:
        payload = {
            "prompt": "A cute digital robot holding a paintbrush, minimalist art style",
            "name": "Test NFT Robot",
            "description": "A test NFT generated by the AI NFT Minter"
        }
        
        print("   ⏳ Generating NFT (this may take 10-30 seconds)...")
        response = requests.post(
            f"{BASE_URL}/api/v1/generate-nft",
            json=payload,
            timeout=60
        )
        
        if response.status_code == 200:
            data = response.json()
            if data.get('success'):
                print(f"   ✅ NFT generated successfully!")
                print(f"   Image: {data.get('image_path')}")
                print(f"   Metadata: {data.get('metadata_path')}")
                print(f"   Filename: {data.get('filename')}")
            else:
                print(f"   ❌ Generation failed: {data.get('error')}")
        else:
            print(f"   ❌ Failed: {response.status_code}")
            print(f"   Response: {response.text}")
    except Exception as e:
        print(f"   ❌ Error: {e}")
else:
    print("   ⏭️  Skipping - GOOGLE_API_KEY not configured")

print("\n" + "=" * 60)
print("\n✅ API Testing Complete!")
print("\nTo use the API:")
print("  - Interactive Docs: http://localhost:8000/docs")
print("  - Generate NFT: POST /api/v1/generate-nft")
print("  - Batch Generate: POST /api/v1/generate-batch")
